#!/bin/sh

VERSION="$1"
if test -z "$VERSION"; then
	echo "Usage: $0 VERSION"
	exit 1
fi

set -e
docker buildx build --platform linux/arm64,linux/amd64,linux/arm/v7 -t lule75/btsdev2:"$VERSION" -t lule75/btsbtsdev2:latest --push .
